from termcolor import cprint
def man_page():
    cprint("NAME","cyan")
    print("     X-Scrapper - WCSC - A Web Crawler and Scrapper ")
    cprint("SYNOPSIS","cyan")
    cprint("     X-Scrapper","cyan",end="")
    print(" is a program for crawling and scrapping the web. It is used to store")
    print("     links, images ,mails and screen-shots of websites it visits.We may want data of")
    print("     a particular website,so this tool becomes handy and useful for getting required")
    print("     data.")
    cprint("OPTIONS","cyan")
    cprint("    -url","cyan",end="          ")
    print("=",end=" ")
    print("URL of website to Scrap")
    cprint("    -depth","cyan",end="          ")
    print("=",end=" ")
    print("for entering depth value while scrapping")
    print("Optional Flags:")
    cprint("    -h or head","cyan",end="     ")
    print("=",end=" ")
    print("for printing headers to stdout")
    cprint("    -img or images","cyan",end=" ")
    print("=",end=" ")
    print("for printing images to stdout")
    cprint("    -l or link","cyan",end="     ")
    print("=",end=" ")
    print("for printing links to stdout")
    cprint("    -m or mails","cyan",end="    ")
    print("=",end=" ")
    print("for printing mails to stdout")
    cprint("    -help","cyan",end="          ")
    print("=",end=" ")
    print("for help")
    cprint("EXAMPLES","cyan")
    print("     The following command will print links of websites founded on website to console output")
    cprint("             WCSC.py -url 'url' -depth 'depth' -l","cyan")
    print("     The following command will print links of images founded on website to console output")
    cprint("             WCSC.py -url 'url' -depth 'depth' -img","cyan")
    print("     The following command will print headers founded on website to console output")
    cprint("             WCSC.py -url 'url' -depth 'depth' -h","cyan")
    print("     The following command will print mails founded on website to console output")
    cprint("             WCSC.py -url 'url' -depth 'depth' -m","cyan")
    cprint("AUTHOR","cyan")
    print("     This Tool was written by",end="")
    cprint("Ayush Budhiraja","cyan",end="")
    print(",who can we reached by",end="")
    cprint(" ayushbudhiraja795@gmail.com","cyan")
    